name: eshrm_mobile
description: "A new Flutter project."
publish_to: 'none' 
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  camera: ^0.11.2+1         
  path_provider: ^2.1.5    
  path: ^1.9.1             
  provider: ^6.1.2
  geolocator: ^12.0.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  connectivity_plus: ^7.0.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/vector.png